apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: namespace-workflow-1708119046296
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082